[[redirects]]
  from = "/ffastats/*"
  to = "/ffastats.html"
  force = true
  status = 200

[[redirects]]
  from = "/FFAStats/*"
  to = "/ffastats.html"
  status = 200

[[redirects]]
  from = "/FFAstats/*"
  to = "/ffastats.html"
  status = 200
